### ISSUE TITLE
Problem starting the container

### ISSUE THREAD

**Issue by SalahAdDin** [shadowhand/opus-docker#2]
I have this problem each time that i start the container:

```bash
ERROR: for redis  ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

ERROR: for web  Cannot start service web: b'open /dev/mapper/docker-8:6-4489802-8e91836b25af5bb60fd94bac2415864ccddcb5cce30a6598a67adf4d29888918: no such file or directory'
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
```
I tried restarting the docker machine and i get now this error:
```bash
docker-machine restart                                                                                  1 ↵  5724  17:32:52 
Restarting "default"...
(default) Check network to re-create if needed...
(default) Waiting for an IP...
Waiting for SSH to be available...
Detecting the provisioner...
Restarted machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
 salahaddin@TulipanROG  ~/Proyectos/opus-docker   master  docker-machine env                                                                                        ✓  5725  17:33:52 
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/home/salahaddin/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell: 
# eval $(docker-machine env)
 salahaddin@TulipanROG  ~/Proyectos/opus-docker   master  eval $(docker-machine env)                                                                                ✓  5726  17:34:02 
 salahaddin@TulipanROG  ~/Proyectos/opus-docker   master  bin/start                                                                                                 ✓  5727  17:34:48 
Starting Opus version v1.0.0 ...

Switching to version v1.0.0 ...
error: pathspec 'v1.0.0' did not match any file(s) known to git.
bin/start: línea 23: composer: no se encontró la orden
/home/salahaddin/Proyectos/opus-docker
Starting Opus at http://192.168.99.100/ ...
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.11.2', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 64, in main
    command()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 116, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 876, in up
    remove_orphans=remove_orphans)
  File "/usr/lib/python3.6/site-packages/compose/project.py", line 385, in up
    warn_for_swarm_mode(self.client)
  File "/usr/lib/python3.6/site-packages/compose/project.py", line 590, in warn_for_swarm_mode
    info = client.info()
  File "/usr/lib/python3.6/site-packages/docker/api/daemon.py", line 73, in info
    return self._result(self._get(self._url("/info")), True)
  File "/usr/lib/python3.6/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 183, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 390, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/lib/python3.6/site-packages/docker/transport/ssladapter.py", line 56, in get_connection
    conn = super(SSLAdapter, self).get_connection(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 296, in get_connection
    conn = self.poolmanager.connection_from_url(url)
  File "/usr/lib/python3.6/site-packages/urllib3/poolmanager.py", line 271, in connection_from_url
    pool_kwargs=pool_kwargs)
  File "/usr/lib/python3.6/site-packages/urllib3/poolmanager.py", line 219, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/lib/python3.6/site-packages/urllib3/poolmanager.py", line 230, in connection_from_context
    pool_key = pool_key_constructor(request_context)
  File "/usr/lib/python3.6/site-packages/urllib3/poolmanager.py", line 95, in _default_key_normalizer
    return key_class(**context)
TypeError: __new__() got an unexpected keyword argument 'key_assert_hostname'

```

Any idea?

**Comment by shadowhand** [comment]
I am not sure what `no se encontró la orden` means, but it looks like you don't have `composer` installed.

**Comment by shadowhand** [comment]
See also #1

**Comment by SalahAdDin** [comment]
Was a problem with `composer` version.
